orc: use 4 spaces instead of tabs in python tasks
* newer oe-core is using 4 spaces and python code will fail with IndentationError
  when we prepend tab indentation to such task (e.g. populate_packages, clean)
  NOTE: Error during finalise of meta-oe/recipes-devtools/orc/orc_0.4.14.bb
  ERROR: ExpansionError during parsing meta-oe/recipes-devtools/orc/orc_0.4.14.bb:
    Failure expanding variable populate_packages:
    IndentationError: unindent does not match any outer indentation level (<string>, line 4)
* there is also check in bitbake:
  WARNING: Variable populate_packages contains tabs, please remove these
  (meta-oe/recipes-devtools/orc/orc_0.4.14.bb)

Open-webOS-DCO-1.0-Signed-off-by: Martin Jansa <martin.jansa@palm.com>
Change-Id: Ic815d2ec4872d10dfcadf05e50629597aba649c9
Reviewed-on: http://g2g.palm.com/1092
Reviewed-by: Build Verification
Reviewed-by: Iyad Qumei <iyad.qumei@palm.com>
Tested-by: Martin Jansa <martin.jansa@palm.com>